name: Deploy Frontend App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: false

      - name: Install Packages
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Restart frontend-app on VPS
        run: pm2 restart frontend-app
